apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    app: online-inference-2
spec:
  containers:
    - image: creativecrisis/online_inference:v1
      name: online-inference-2
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"