apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
  labels:
    app: online-inference-6
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: online-inference-6
  template:
    metadata:
      name: online-inference-6
      labels:
        app: online-inference-6
    spec:
      containers:
        - image: creativecrisis/online_inference:v1
          name: online-inference-6
          ports:
            - containerPort: 8000
