apiVersion: v1
kind: Pod
metadata:
  name: probes-pod
  labels:
    app: online-inference-3
spec:
  containers:
    - image: creativecrisis/online_inference:v2
      name: online-inference-3
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 15
      readinessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 15
